name: Terraform Apply, Docker Build, and Push

on:
  push:
    branches:
      - main

jobs:
  apply_build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Build Docker Image
        run: docker build -t my-webapp-image .

      - name: Log in to Amazon ECR
        run: aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 178695293962.dkr.ecr.us-east-2.amazonaws.com

      - name: Tag Docker Image
        run: docker tag my-webapp-image:latest 178695293962.dkr.ecr.us-east-2.amazonaws.com/webapp24:latest

      - name: Push Docker Image to Amazon ECR
        run: docker push 178695293962.dkr.ecr.us-east-2.amazonaws.com/webapp24:latest

      - name: Terraform Init
        run: terraform init

      - name: Terraform plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve

  destroy_terraform:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'  # Trigger only when manually triggered

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
    

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
